#!/usr/bin/env python3
"""tools/fabric/ssh_hosts.py and the registry's `sshd` shape (agent-fabric
ADR-048 §5 rule 5).

known_hosts comes from the registry only; `check` compares the pin with a
scratch /etc/ssh (AGENT_FABRIC_SSH_ETC) and fails on any difference; lint
admits null, absent and a well-formed pin, and refuses every malformed one
on both validators (jsonschema where installed, the standard-library one
the pinned interpreter runs). Plain script: ok/FAIL, exit 1 on a failure."""
from __future__ import annotations

import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
from typing import Any

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "tools", "fabric"))
import lint  # noqa: E402
from lint_rules import schema as lint_schema  # noqa: E402

TOOL = os.path.join(ROOT, "tools", "fabric", "ssh_hosts.py")
ED = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGb1y2fxD0RkCq3dHn2iN8f3mR1vD0n1QvJx2v0r2X7a"
EC = "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHx1="
HERE_HOST = socket.gethostname().split(".")[0]


def registry(tmp: str, hosts: dict[str, Any]) -> str:
    root = os.path.join(tmp, "fabric")
    os.makedirs(os.path.join(root, "runtime", "hosts"), exist_ok=True)
    if not os.path.isdir(os.path.join(root, "runtime", "hosts", "schema")):
        shutil.copytree(os.path.join(ROOT, "runtime", "hosts", "schema"), os.path.join(root, "runtime", "hosts", "schema"))
    full = {h: {"platform": "fedora", "ssh": None if i == 0 else f"op@{h}", "operator": "user",
                "fabric": "~/projects/agent-fabric", **extra} for i, (h, extra) in enumerate(hosts.items())}
    path = os.path.join(root, "runtime", "hosts", "registry.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump({"version": 1, "description": "fixture", "placement": {"user": next(iter(hosts))}, "hosts": full}, fh)
    return root


def tool(root: str, *args: str, etc: str = "") -> subprocess.CompletedProcess[str]:
    env = {**os.environ, "AGENT_FABRIC_HOSTS_REGISTRY": os.path.join(root, "runtime", "hosts", "registry.json"),
           "AGENT_FABRIC_SSH_ETC": etc}
    return subprocess.run([sys.executable, TOOL, *args], env=env, capture_output=True, text=True, timeout=30)


def etc_with(tmp: str, *keys: str) -> str:
    d = os.path.join(tmp, "etc-ssh")
    os.makedirs(d, exist_ok=True)
    for i, k in enumerate(keys):
        with open(os.path.join(d, f"ssh_host_{i}_key.pub"), "w", encoding="utf-8") as fh:
            fh.write(f"{k} root@template\n")
    return d


def both_validators(root: str) -> list[list[str]]:
    """The findings with jsonschema (when present) and without it."""
    out = [lint.host_registry_findings(root)]
    real = lint_schema.validate_json
    lint_schema.validate_json = lambda s, d, w: lint_schema._structural_check(s, d, w)  # type: ignore[assignment]
    try:
        import lint_rules.shape as shape
        saved = shape.validate_json
        shape.validate_json = lint_schema.validate_json
        try:
            out.append(lint.host_registry_findings(root))
        finally:
            shape.validate_json = saved
    finally:
        lint_schema.validate_json = real
    return out


PIN = {"address": "127.0.0.1", "port": 22, "host_keys": [ED, EC]}


def test_known_hosts_lists_pinned_hosts_only() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = registry(tmp, {"aaa": {"sshd": PIN}, "bbb": {"sshd": None}, "ccc": {},
                              "ddd": {"sshd": {"address": "10.0.0.5", "port": 2222, "host_keys": [ED]}}})
        r = tool(root, "known-hosts")
        lines = r.stdout.splitlines()
        assert r.returncode == 0, r.stderr
        assert lines[0].startswith("# generated by fabric-ssh-hosts"), lines
        assert lines[1:] == [f"127.0.0.1 {ED}", f"127.0.0.1 {EC}", f"[10.0.0.5]:2222 {ED}"], lines


def test_check_matches_and_ignores_the_comment() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = registry(tmp, {HERE_HOST: {"sshd": PIN}})
        r = tool(root, "check", HERE_HOST, etc=etc_with(tmp, EC, ED))
        assert (r.returncode, r.stdout.strip()) == (0, "match"), (r.returncode, r.stdout, r.stderr)


def test_check_fails_on_any_difference() -> None:
    other = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOtherOtherOtherOtherOtherOtherOtherOther12"
    for on_host, want in (([ED], ["only in the registry: " + EC]),
                          ([ED, EC, other], ["only on the host: " + other]),
                          ([other, EC], ["only in the registry: " + ED, "only on the host: " + other])):
        with tempfile.TemporaryDirectory() as tmp:
            root = registry(tmp, {HERE_HOST: {"sshd": PIN}})
            r = tool(root, "check", HERE_HOST, etc=etc_with(tmp, *on_host))
            assert r.returncode == 1 and r.stdout.splitlines() == want, (on_host, r.stdout, r.stderr)


def test_check_refuses_what_it_cannot_compare() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = registry(tmp, {HERE_HOST: {"sshd": None}, "elsewhere-x": {"sshd": PIN}})
        etc = etc_with(tmp, ED)
        for args, why in ((["check", HERE_HOST], "no pinned sshd"), (["check", "elsewhere-x"], "is not this host"),
                          (["check", "nowhere"], "no host")):
            r = tool(root, *args, etc=etc)
            assert r.returncode == 1 and why in r.stderr and r.stdout == "", (args, r.stdout, r.stderr)
        root = registry(tmp, {HERE_HOST: {"sshd": PIN}})
        r = tool(root, "check", HERE_HOST, etc=os.path.join(tmp, "empty"))
        assert r.returncode == 1 and "no ssh_host_" in r.stderr, r.stderr


def test_lint_admits_null_absent_and_a_pin() -> None:
    for extra in ({"sshd": None}, {}, {"sshd": PIN}, {"sshd": {"address": "::1", "port": 2222, "host_keys": [ED]}}):
        with tempfile.TemporaryDirectory() as tmp:
            root = registry(tmp, {"h": extra})
            for f in both_validators(root):
                assert f == [], (extra, f)


def test_lint_refuses_a_malformed_pin() -> None:
    bad = {
        "a name, not an address": {**PIN, "address": "localhost"},
        "port zero": {**PIN, "port": 0},
        "port as a string": {**PIN, "port": "22"},
        "no keys": {**PIN, "host_keys": []},
        "a key with its comment": {**PIN, "host_keys": [ED + " root@h"]},
        "an unknown key type": {**PIN, "host_keys": ["ssh-dss AAAAB3NzaC1kc3M="]},
        "a missing port": {"address": "127.0.0.1", "host_keys": [ED]},
        "an extra field": {**PIN, "user": "op"},
        "a string": "127.0.0.1",
    }
    for label, sshd in bad.items():
        with tempfile.TemporaryDirectory() as tmp:
            root = registry(tmp, {"h": {"sshd": sshd}})
            for f in both_validators(root):
                assert f and "sshd" in " ".join(f), (label, f)


def test_lint_refuses_two_hosts_at_one_address() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = registry(tmp, {"h1": {"sshd": PIN}, "h2": {"sshd": PIN}})
        f = lint.host_registry_findings(root)
        assert any("share the sshd address 127.0.0.1:22" in x for x in f), f


def test_the_committed_registry_passes() -> None:
    """The operator's own registry, on purpose, through roots as a reader asks for it."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("fabric_roots", os.path.join(ROOT, "tools", "fabric", "roots.py"))
    roots = importlib.util.module_from_spec(spec); spec.loader.exec_module(roots)
    path = roots.hosts_registry(engine=ROOT, environ={k: v for k, v in os.environ.items() if k != roots.ENV_HOSTS_REGISTRY})
    if not os.path.isfile(path):
        print(f"  skip test_the_committed_registry_passes: no hosts registry at {path}")
        return
    reg = json.load(open(path, encoding="utf-8"))
    env = {**os.environ, "AGENT_FABRIC_HOSTS_REGISTRY": path}
    r = subprocess.run([sys.executable, TOOL, "known-hosts"], env=env, capture_output=True, text=True, timeout=30)
    pinned = sum(len(e["sshd"]["host_keys"]) for e in reg["hosts"].values() if isinstance(e.get("sshd"), dict))
    assert r.returncode == 0 and len(r.stdout.splitlines()) == 1 + pinned, (r.stdout, r.stderr)


def main() -> int:
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    failed = 0
    for t in tests:
        try:
            t()
            print(f"  ok   {t.__name__}")
        except AssertionError as exc:
            failed += 1
            print(f"  FAIL {t.__name__}: {exc}")
    print(f"\n{len(tests) - failed}/{len(tests)} passed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
