#!/usr/bin/env python3
"""tools/fabric/ssh_hosts.py — the hosts' pinned ssh host keys
(agent-fabric ADR-048 §5 rule 5), behind bin/fabric-ssh-hosts.

    fabric-ssh-hosts known-hosts      known_hosts lines for every pinned host
    fabric-ssh-hosts check <host>     the pin against this host's own keys

CONTRACT
  A host's sshd is its registry entry's `sshd` (runtime/hosts/registry.json):
  null or absent until provisioned, else {"address", "port", "host_keys"},
  each key `<type> <base64>` with no comment. The shape is the hosts
  schema's; lint holds it. `ssh` is a different property — the
  coordinator's destination for the host's operator account — and is not
  read here.
  known-hosts  one line per pinned key, `<address> <type> <base64>`, the
               address as `[address]:port` off port 22, after one comment
               line naming the source. A host that is not pinned has no
               line: known_hosts comes from the registry or not at all,
               never from ssh-keyscan.
  check        reads /etc/ssh/ssh_host_*_key.pub (AGENT_FABRIC_SSH_ETC
               overrides the directory, for a test) and compares the set
               of `<type> <base64>` with the pin. Run on the host itself:
               a <host> other than this one's short hostname is refused,
               because the files read would be another host's.
  env     AGENT_FABRIC_HOSTS_REGISTRY, AGENT_FABRIC_SSH_ETC
  stdout  known_hosts lines; check: `match` or one line per difference
  stderr  every refusal, one line `fabric-ssh-hosts: <why>`
  exit    0 done or the keys match; 1 a difference, an unpinned or unknown
          host, an unreadable registry or key directory; 2 usage
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import socket
import sys
from typing import Any

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import roots  # noqa: E402

PROG = "fabric-ssh-hosts"


class Refused(Exception):
    pass


def load_registry() -> dict[str, Any]:
    path = roots.hosts_registry()
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError) as exc:
        raise Refused(f"cannot read the host registry {path}: {exc}") from exc


def key_of(line: str) -> str | None:
    """`<type> <base64>` of a public-key line, its comment dropped: the
    comment of a host's .pub is `root@<template>` on Qubes, which says
    nothing about the key."""
    parts = line.split()
    return f"{parts[0]} {parts[1]}" if len(parts) >= 2 else None


def known_host_pattern(sshd: dict[str, Any]) -> str:
    # ssh writes a non-default port as [host]:port; a bare address there
    # would never match a connection to that port.
    port = sshd.get("port", 22)
    address = sshd["address"]
    return address if port == 22 else f"[{address}]:{port}"


def known_hosts(reg: dict[str, Any]) -> list[str]:
    lines = ["# generated by fabric-ssh-hosts from runtime/hosts/registry.json (ADR-048); never edited, never keyscanned"]
    for hid, entry in sorted((reg.get("hosts") or {}).items()):
        sshd = entry.get("sshd") if isinstance(entry, dict) else None
        if not isinstance(sshd, dict):
            continue
        for k in sshd.get("host_keys") or []:
            lines.append(f"{known_host_pattern(sshd)} {k}")
    return lines


def host_keys_here(etc: str) -> set[str]:
    found: set[str] = set()
    for path in sorted(glob.glob(os.path.join(etc, "ssh_host_*_key.pub"))):
        try:
            with open(path, encoding="utf-8") as fh:
                k = key_of(fh.read())
        except OSError as exc:
            raise Refused(f"cannot read {path}: {exc}") from exc
        if k:
            found.add(k)
    return found


def check(reg: dict[str, Any], host: str, etc: str, here: str) -> list[str]:
    """The differences between the pin and this host's keys, one line each."""
    entry = (reg.get("hosts") or {}).get(host)
    if not isinstance(entry, dict):
        raise Refused(f"no host {host!r} in the registry")
    if host != here:
        raise Refused(f"{host!r} is not this host ({here!r}); run check on the host whose keys it pins")
    sshd = entry.get("sshd")
    if not isinstance(sshd, dict):
        raise Refused(f"{host!r} has no pinned sshd; pin the keys ssh-operator.sh printed first")
    pinned = {k for k in (key_of(x) for x in sshd.get("host_keys") or []) if k}
    actual = host_keys_here(etc)
    if not actual:
        raise Refused(f"no ssh_host_*_key.pub under {etc}")
    out = [f"only in the registry: {k}" for k in sorted(pinned - actual)]
    out += [f"only on the host: {k}" for k in sorted(actual - pinned)]
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog=PROG, description="The hosts' pinned ssh host keys (ADR-048).")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("known-hosts", help="known_hosts lines for every pinned host")
    c = sub.add_parser("check", help="the pin against this host's /etc/ssh/ssh_host_*_key.pub")
    c.add_argument("host")
    args = ap.parse_args(argv)
    try:
        reg = load_registry()
        if args.cmd == "known-hosts":
            print("\n".join(known_hosts(reg)))
            return 0
        diffs = check(reg, args.host, os.environ.get("AGENT_FABRIC_SSH_ETC") or "/etc/ssh",
                      socket.gethostname().split(".")[0])
    except Refused as exc:
        print(f"{PROG}: {exc}", file=sys.stderr)
        return 1
    print("\n".join(diffs) if diffs else "match")
    return 1 if diffs else 0


if __name__ == "__main__":
    sys.exit(main())
